COMMENT = a collection of cache libraries in the same API interface

MODPY_EGG_VERSION = 0.4.1
DISTNAME = 			cachelib-${MODPY_EGG_VERSION}
PKGNAME =			py-${DISTNAME}
REVISION =			0

CATEGORIES =		devel
HOMEPAGE =			https://github.com/pallets/cachelib/

MAINTAINER =		Thaison Nguyen <thieson08@me.com>

# BSD3
PERMIT_PACKAGE =	Yes

MODULES =			lang/python

MODPY_SETUPTOOLS =	Yes
MODPY_PI =			Yes
MODPY_PYTEST =		Yes					

FLAVORS =			python3
FLAVOR =			python3

.include <bsd.port.mk>
