COMMENT = Checks for unsafe or broken printer firmwares

MODPY_EGG_VERSION = 2021.10.11
DISTNAME = 			OctoPrint-FirmwareCheck-${MODPY_EGG_VERSION}
PKGNAME =			py-${DISTNAME}
REVISION =			0

CATEGORIES =		print
HOMEPAGE =			https://github.com/OctoPrint/OctoPrint-FirmwareCheck

MAINTAINER =		Thaison Nguyen <thieson08@me.com>

# AGPLv3
PERMIT_PACKAGE =	Yes

MODULES =			lang/python

MODPY_SETUPTOOLS =	Yes
MODPY_PI =			Yes

FLAVORS =			python3
FLAVOR =			python3

.include <bsd.port.mk>
