COMMENT = Least recently used (lru) cache implementation

MODPY_EGG_VERSION = 		1.2.0
DISTNAME = 			pylru-${MODPY_EGG_VERSION}
PKGNAME =			py-${DISTNAME}
REVISION =			0

CATEGORIES =		devel
HOMEPAGE =		https://github.com/jlhutch/pylru
MASTER_SITES =		https://pypi.python.org/packages/source/p/pylru


MAINTAINER =		Thaison Nguyen <thieson08@me.com>

# GPL
PERMIT_PACKAGE =	YES

MODULES =		lang/python

MODPY_SETUPTOOLS =	YES
MODPY_PI =		Yes
MODPY_PI_DIR =		p/pylru

FLAVORS =			python3
FLAVOR =			python3

.include <bsd.port.mk>
