COMMENT = Python 3 port of sgmllib

MODPY_EGG_VERSION = 1.0.0
DISTNAME = 			sgmllib3k-${MODPY_EGG_VERSION}
PKGNAME =			py-${DISTNAME}
REVISION =			0

CATEGORIES =		devel
HOMEPAGE =			https://pypi.python.org/pypi/sgmllib3k

MAINTAINER =		Thaison Nguyen <thieson08@me.com>

# BSD2CLAUSE
PERMIT_PACKAGE =	Yes

MODULES =			lang/python

MODPY_SETUPTOOLS =	Yes
MODPY_PI =			Yes
					

FLAVORS =			python3
FLAVOR =			python3

.include <bsd.port.mk>
