COMMENT = Provides additional information about your Pi in the UI

MODPY_EGG_VERSION = 2021.10.28
DISTNAME = 			OctoPrint-PiSupport-${MODPY_EGG_VERSION}
PKGNAME =			py-${DISTNAME}
REVISION =			0

CATEGORIES =		print
HOMEPAGE =			https://github.com/OctoPrint/OctoPrint-PiSupport

MAINTAINER =		Thaison Nguyen <thieson08@me.com>

# AGPLv3
PERMIT_PACKAGE =	Yes

MODULES =			lang/python

MODPY_SETUPTOOLS =	Yes
MODPY_PI =			Yes

FLAVORS =			python3
FLAVOR =			python3

.include <bsd.port.mk>
