COMMENT = 		Add colours to the output of Python logging module

MODPY_EGG_VERSION = 	6.6.0
DISTNAME = 		colorlog-${MODPY_EGG_VERSION}
PKGNAME =			py-${DISTNAME}
REVISION =			0

CATEGORIES =		www
HOMEPAGE =			https://github.com/borntyping/python-colorlog

MAINTAINER =		Thaison Nguyen <thieson08@me.com>

# MIT
PERMIT_PACKAGE =	Yes

MODULES =			lang/python

MODPY_SETUPTOOLS =	Yes
MODPY_PI =			Yes
					

FLAVORS =			python3
FLAVOR =			python3

.include <bsd.port.mk>
