COMMENT = python wrapper for subprocess

MODPY_EGG_VERSION = 		0.1.6
DISTNAME = 			sarge-${MODPY_EGG_VERSION}
PKGNAME =			py-${DISTNAME}
REVISION =			0

CATEGORIES =		devel
HOMEPAGE =		https://docs.red-dove.com/sarge/

#Pypi doesnt work somehow. makesum reports missing master site
MASTER_SITES = https://bitbucket.org/vinay.sajip/sarge/downloads/

MAINTAINER =		Thaison Nguyen <thieson08@me.com>

# BSD
PERMIT_PACKAGE =	Yes

MODULES =		lang/python

#MODPY_SETUPTOOLS =	Yes
#MODPY_PI =		Yes	

FLAVORS =			python3
FLAVOR =			python3

.include <bsd.port.mk>
