COMMENT = Media asset management for Python and various web frameworks

MODPY_EGG_VERSION = 2.0
DISTNAME = 		webassets-${MODPY_EGG_VERSION}
PKGNAME =		py-${DISTNAME}
REVISION =		0

CATEGORIES =		www
HOMEPAGE =		http://github.com/miracle2k/webassets/

MAINTAINER =		Thaison Nguyen <thieson08@me.com>

# BSD
PERMIT_PACKAGE =	Yes

MODULES =		lang/python

MODPY_SETUPTOOLS =	Yes
MODPY_PI =		Yes

FLAVORS =			python3
FLAVOR =			python3

.include <bsd.port.mk>
