COMMENT = validate a string such as file-paths

MODPY_EGG_VERSION = 2.5.0
DISTNAME = pathvalidate-${MODPY_EGG_VERSION}
PKGNAME =			py-${DISTNAME}
REVISION =			0

CATEGORIES =		devel
HOMEPAGE =			https://github.com/tombashi/pathvalidate

MAINTAINER =		Thaison Nguyen <thieson08@me.com>

# BSD
PERMIT_PACKAGE =	Yes

MODULES =			lang/python

MODPY_SETUPTOOLS =	Yes
MODPY_PI =			Yes
#Test needs too many dependencies
#MODPY_PYTEST =		Yes

FLAVORS =			python3
FLAVOR =			python3

.include <bsd.port.mk>
