COMMENT = Zipfile generator that takes streams

MODPY_EGG_VERSION = 		1.1.8
DISTNAME = 			zipstream-new-${MODPY_EGG_VERSION}
PKGNAME =			py-${DISTNAME}
REVISION =			0

CATEGORIES =		www
HOMEPAGE =			https://github.com/arjan-s/python-zipstream

MAINTAINER =		Thaison Nguyen <thieson08@me.com>

# GPLv3
PERMIT_PACKAGE =	Yes

MODULES =			lang/python

MODPY_SETUPTOOLS =	Yes
MODPY_PI =			Yes

#No tests found somehow
#MODPY_PYTEST =		Yes
#TEST_DEPENDS =		devel/py-nose${MODPY_FLAVOR}

FLAVORS =			python3
FLAVOR =			python3

.include <bsd.port.mk>
