COMMENT = 				Immutable wrapper around dictionaries

MODPY_EGG_VERSION =		2.2.1
DISTNAME =				immutabledict-${MODPY_EGG_VERSION}
PKGNAME =				py-${DISTNAME}
REVISION =				0

CATEGORIES =			devel

HOMEPAGE =				https://github.com/corenting/immutabledict

MAINTAINER =			Thaison Nguyen <thieson08@me.com>

# MIT
PERMIT_PACKAGE =		Yes

MODULES =			lang/python

MODPY_SETUPTOOLS =	Yes
MODPY_PI =			Yes
MODPY_PYTEST =		Yes

# RUN_DEPENDS =	

FLAVORS =			python3
FLAVOR =			python3

.include <bsd.port.mk>
